name: TownyWars
version: 1.1.4
authors: [DanielRHarris]
main: main.java.com.danielrharris.townywars.TownyWars
depend: [Towny]
commands:
  twar:
    usage: No permission!
  twar neutral:
    permission: townywars.neutral
    usage: Syntax error! Perhaps you meant /twar neutral [nation]